# Site settings
title: Hojjat Abedi's CV
description: Hojjat Abedi's CV
baseurl: https://glinboy.com
url: https://glinboy.com
favicon: /assets/img/avatar.JPG
rss_url: /pages/atom.xml
google_analytics: UA-15495320-5

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Hojjat Abedi
  gender: Male
  # gender: Female
  brithday: July 1986
  maritalStatus: Married
  title: Java Developer
  address: Tehran, Iran
  email: hojjatabedie#gmail.com
  link: http://glinboy.com
  github: glinboy
  linkedin: hojjatabedie
  twitter: glinboy
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow: 2670847
  workHistory:
    - work1:
      company: Rayan Ham-Afza
      location: Tehran, Iran
      title: Java Developer (Back-end)
      started: 2017
      duration: (Apr 2017 - Nov 2018)
      description: Rayan Ham-Afza main field of activity is developing software for stock brokers, investment funds and banks and software services accordingly.
    - work2:
      company: Technology Hafiz System
      location: Tehran, Iran
      title: Oracle ADF Developer
      started: 2013
      duration: (Dec 2013 - Apr 2017)
      description: Hafiz Samean Technology Co. was founded in 2000 and has been working on budgeting and budgeting in the areas of designing of organizational systems and processes, auditing, as well as analyzing and designing and deploying MIS software in government, business and contracting industries.
    - work3:
      company: Freelancer
      location: Tehran, Iran
      title: Web Designer
      started: 2010
      duration: (2010 - Dec 2013)
      description: I designed web site with Jomla, Wordpress and Drupal for commerical and personal use. I used HTML, CSS and Javascript for run websites.
  educationHistory:
    - education1:
      organization: Payame Noor University
      location: Tehran, Iran
      degree: Bachelor
      major: Computer Software Engineering
      started: 2008
      duration: (Sep 2008 - Drop-out)
      description: Payame Noor University is a public university system and one of the largest universities in Iran.
  personalProjects:
    - project1:
      name: J-Cart
      description: Yet Another Cart Application On Cutting-Edge of Java Technologies With Sprin Boot
      platforms: Web, Mobile
      started: 2018
      license: Open Source
      website: https://github.com/GLinBoy/jcart-backend
      github: https://github.com/GLinBoy/jcart-backend
      technologies: Spring-Boot, JPA, gradle, RESTful
    - project2:
      name: Feader
      description: Yet Another Feed Reader Inspired by <a href="https://feedly.com">https://feedly.com <small><i class="fa fa-external-link"></i></small></a>
      platforms: Web, Mobile, Desktop
      started: 2018
      license: Open Source
      website: https://github.com/GLinBoy/feader
      github: https://github.com/GLinBoy/feader
      technologies: Spring-Boot, Spring Batch, JPA, Maven, RESTful, thymleaf
  languages:
    - language1:
      name: Persian (Farsi)
      proficiency: Native
    - language2:
      name: English
      proficiency: Pre-advanced
  programmingSkills:
    - skill1:
      name: Java/Java EE
      percentage: 70%
    - skill2:
      name: HTML/CSS/JS
      percentage: 90%
    - skill3:
      name: VueJS
      percentage: 50%
    - skill4:
      name: C++
      percentage: 40%
    - skill5:
      name: Python
      percentage: 40%
  programmingTools:
    - tools1:
      name: Frameworks
      data: Oracle ADF, Spring & Spring Boot, Hibernate, JUnit, VueJS
    - tools2:
      name: Technologies
      data: JPA, SOAP, RESTful, AJAX, MicroService
    - tools3:
      name: Development Tool​s
      data: Linux, Spring Tool Suite, Eclipse IDE, Intellij, Netbeans, Maven, Git, SVN
    - tools4:
      name: Application Server​s
      data: Weblogic10.3, Wildfly, Jetty, Tomcat
    - tools5:
      name: Database​s
      data: Oracle 11g, MySQL
